workflows:
  my-workflow:
    name: Build App
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      flutter: 3.27.4
      vars:
        CM_SECRET: $CM_SECRET
        GOOGLE_SERVICES_JSON: $GOOGLE_SERVICES_JSON
        GOOGLE_SERVICES_INFO_PLIST: $GOOGLE_SERVICES_INFO.PLIST

    scripts:
      - name: Get Flutter Dependencies
        script: flutter pub get

      - name: Create local.properties for Codemagic
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          echo "flutter.sdk=$FLUTTER_ROOT" >> android/local.properties

      - name: Decode google-services.json
        script: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json

      - name: Decode GoogleService-Info_plist
        script: |
          echo $GOOGLE_SERVICES_INFO.PLIST | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Decode secrets
        script: echo $CM_SECRET | base64 --decode > codemagic.yaml.secret

      - name: Run Flutter Tests with Coverage
        script: flutter test --coverage

      - name: Build Android APK
        script: flutter build apk --release -v

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - coverage/lcov.info    # رفع ملف التغطية لتتمكن من تحميله ومراجعته

    publishing:
      email:
        recipients:
          - ahmedali205001@gmail.com

