name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      GOOGLE_SERVICES_INFO_PLIST: ${{ secrets.GOOGLE_SERVICES_INFO_PLIST }}
      CM_SECRET: ${{ secrets.CM_SECRET }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Decode google-services.json
        run: |
          mkdir -p android/app
          echo "$GOOGLE_SERVICES_JSON" | base64 --decode > android/app/google-services.json

      - name: Decode GoogleService-Info.plist
        run: |
          mkdir -p ios/Runner
          echo "$GOOGLE_SERVICES_INFO_PLIST" | base64 --decode > ios/Runner/GoogleService-Info.plist

      - name: Decode codemagic.yaml.secret
        run: |
          mkdir -p secrets
          echo "$CM_SECRET" | base64 --decode > secrets/codemagic.yaml.secret

      - name: Deploy to Firebase
        run: firebase deploy --token "$FIREBASE_TOKEN"
